# Generated by Django 4.1.1 on 2022-12-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_skill_skillicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='certificate',
            field=models.ImageField(default='cv/static/certificates/certificate.png', upload_to='cv/static/certificates/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skillIcon',
            field=models.ImageField(default='cv/static/skillsIcons/icon.png', upload_to='cv/static/skillsIcons/'),
        ),
    ]
